[accessibility]
ui_scale = 1.2000000104308128

[bar]
order = [ "default" ]

    [bar.default]
    capsule = true
    capsule_padding = 3.0
    capsule_radius = 8
    center = [ "clock", "privacy" ]
    contact_shadow = true
    end = [ "clipboard", "network", "bluetooth", "volume", "brightness", "battery", "tray", "notifications" ]
    margin_ends = 44
    padding = 4
    radius = 16
    scale = 1.300000011920929
    start = [ "control-center", "launcher", "wallpaper", "workspaces", "media" ]
    thickness = 30

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
cross_axis_padding = 2
icon_size = 30
main_axis_padding = 4

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@LVDS-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@LVDS-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 800.0
    cy = 718.0
    output = "LVDS-1"
    placement_height = 900.0
    placement_width = 1600.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@LVDS-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[osd.kinds]
lock_keys = false

[shell]
corner_radius_scale = 0.85000001266598701
screen_time_enabled = true

    [shell.animation]
    speed = 1.6000000238418579

    [shell.launcher]
    compact = true

    [shell.panel]
    control_center_placement = "floating"
    control_center_position = "center"
    launcher_placement = "attached"

    [shell.shadow]
    alpha = 0.69999998435378075
    direction = "center"

[theme]
builtin = "Noctalia"
community_palette = "Gruvbox Material Hard"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "vibrant"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "kcolorscheme", "qt", "sway" ]

[wallpaper]
directory = "/home/anvil/Downloads/"
transition = [ "wipe" ]
transition_on_startup = true

    [wallpaper.default]
    path = "/home/anvil/Downloads/wallhaven-1jg1m1.png"

    [wallpaper.last]
    path = "/home/anvil/Downloads/wallhaven-1jg1m1.png"

    [wallpaper.monitors.LVDS-1]
    path = "/home/anvil/Downloads/wallhaven-1jg1m1.png"

[weather]
enabled = false

[widget.audio_visualizer]
bands = 74
mirrored = false
width = 142

[widget.battery]
show_label = false

[widget.bluetooth]
hide_when_adapter_off = true

    [widget.bluetooth.actions]
    right = "none"

[widget.clock]
anchor = true
capsule = true
capsule_opacity = 0.0
format = "{:%H:%M:%S}"

[widget.control-center]
enabled = false

[widget.launcher]
enabled = false

[widget.media]
art_size = 12
font_scale = 0.80000000000000004
hide_artist = true
hide_when_no_media = true
min_length = 0

[widget.network]
show_label = false
vpn_status = "hidden"

[widget.privacy]
hide_inactive = true

[widget.sysmon]
stat = "cpu_temp"
visualization = "none"

[widget.wallpaper]
enabled = false

[widget.workspaces]
style = "minimal"
