[bar]
order = [ "default" ]

    [bar.default]
    background_opacity = 0.79999998211860657
    capsule = true
    capsule_padding = 3.0
    center = [ "clock", "privacy" ]
    contact_shadow = true
    end = [
        "bar",
        "media",
        "clipboard",
        "network",
        "bluetooth",
        "volume",
        "brightness",
        "battery",
        "tray",
        "notifications",
        "session"
    ]
    font_weight = 400
    margin_ends = 5
    padding = 3
    panel_overlap = 0
    scale = 1.300000011920929
    shadow = false
    start = [ "control-center", "launcher", "wallpaper", "workspaces", "taskbar", "active_window" ]
    thickness = 30
    widget_spacing = 2

[calendar]

[control_center]
sidebar = "full"
sidebar_section = "none"
width = 600

    [control_center.calendar]
    show_events_card = false

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "notification"

    [[control_center.shortcuts]]
    type = "dark_mode"

    [[control_center.shortcuts]]
    type = "wallpaper"

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = [ "desktop-widget-0000000000000001", "desktop-widget-0000000000000002" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 320.0
    box_width = 192.0
    cx = 104.0
    cy = 733.5
    output = "LVDS-1"
    placement_height = 900.0
    placement_width = 1600.0
    rotation = 0.0
    type = "media_player"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        layout = "vertical"

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 528.0
    box_width = 464.0
    cx = 240.0
    cy = 306.0
    output = "LVDS-1"
    placement_height = 900.0
    placement_width = 1600.0
    rotation = 0.0
    type = "calendar"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        show_events = false

[dock]
cross_axis_padding = 2
icon_size = 30
main_axis_padding = 4
position = "left"

[hooks]
colors_changed = "sed -i -E 's/^colors-dark/colors/; s/^colors-light/colors2/' ~/.config/foot/themes/noctalia && awk '/^cursor=/{split($0,a,\"=\"); c=a[2]; next} {print} END{print \"\\n[cursor]\\ncolor=\" c}' ~/.config/foot/themes/noctalia > /tmp/foot-noctalia-fixed && swaymsg reload"
theme_mode_changed = "/usr/share/noctalia/assets/templates/gtk/apply.sh --appearance-only $NOCTALIA_THEME_MODE"

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@LVDS-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@LVDS-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 800.0
    cy = 718.0
    output = "LVDS-1"
    placement_height = 900.0
    placement_width = 1600.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@LVDS-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[notification]
max_visible = 2
scale = 0.70000000298023224

[osd.kinds]
lock_keys = false

[plugin_settings."icefish/phone-connect"]
enable_charging_animation = false
state_update_interval = 25

[plugin_settings."noctalia/screen_recorder"]
audio_bitrate = 122
audio_source = "both"
frame_rate = 30
video_encoder = "cpu"
video_qp = 30
video_quality = "medium"
video_source = "focused"

[plugins]
enabled = [ "noctalia/wallhaven", "icefish/phone-connect" ]

[shell]
app_icon_colorize = true
corner_radius_scale = 0.85000001266598701
polkit_agent = true
screen_time_enabled = true

    [shell.animation]
    speed = 1.6000000238418579

    [shell.panel]
    control_center_position = "center"
    open_near_click_control_center = true

    [shell.screen_corners]
    size = 45

    [shell.shadow]
    alpha = 0.69999998435378075
    direction = "center"

    [shell.window_switcher]
    mru = true

[system.monitor]
enabled = false

[theme]
builtin = "Noctalia"
community_palette = "Ayu Blue"
custom_palette = "wallhaven-1jg1m1-vib"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "muted"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "ghostty", "kcolorscheme", "kitty", "qt", "sway" ]
    community_ids = [
        "opencode",
        "spicetify",
        "brave-origin",
        "discord",
        "telegram",
        "libreoffice",
        "vscode",
        "obs",
        "papirus-icons",
        "whitesur-icons",
        "konsole"
    ]

        [theme.templates.user.terminal-sequences]
        input_path = "~/.config/noctalia/templates/terminal-sequences"
        output_path = "~/.cache/terminal-sequences"
        post_hook = "tee /dev/pts/[0-9]* < ~/.cache/terminal-sequences && swaymsg reload"

[wallpaper]
directory = "/home/anvil/Downloads/"
transition = [ "disc" ]
transition_on_startup = true

    [wallpaper.default]
    path = "/home/anvil/Downloads/wallhaven-q26qql.jpg"

    [wallpaper.last]
    path = "/home/anvil/Downloads/wallhaven-q26qql.jpg"

    [wallpaper.monitors.LVDS-1]
    path = "/home/anvil/Downloads/wallhaven-q26qql.jpg"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/anvil/Downloads/d9w1ugp-ef78534c-ea46-4f07-9bcc-e110544df4b8.png"
    theme_mode = "light"
    wallpaper_scheme = "m3-content"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/anvil/Downloads/wallhaven-1jg1m1.png"
    theme_mode = "dark"
    wallpaper_scheme = "m3-content"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/anvil/Downloads/wallhaven-q26qql.jpg"
    theme_mode = "dark"
    wallpaper_scheme = "muted"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/anvil/Downloads/niggaballs.jpg"
    theme_mode = "dark"
    wallpaper_scheme = "vibrant"

[weather]
enabled = false

[widget.active_window]
font_scale = 0.80000000000000004
max_length = 419
min_length = 0

[widget.audio_visualizer]
bands = 74
mirrored = false
width = 142

[widget.bar]
font_scale = 1.3999999999999999
type = "icefish/phone-connect:bar"

[widget.battery]
show_label = false

[widget.bluetooth]
hide_when_adapter_off = true

    [widget.bluetooth.actions]
    right = "none"

[widget.clock]
anchor = true
capsule = true
format = "{:%H:%M:%S}"

[widget.control-center]
enabled = false

[widget.launcher]
enabled = false

[widget.media]
art_size = 12
font_scale = 0.80000000000000004
hide_artist = true
hide_when_no_media = true
min_length = 0

[widget.network]
show_label = false
vpn_status = "hidden"

[widget.privacy]
hide_inactive = true

[widget.sysmon]
stat = "cpu_temp"
visualization = "none"

[widget.taskbar]
icon_scale = 0.75
inactive_opacity = 0.80000000000000004
item_spacing = 1

[widget.tray]
scale = 0.75

[widget.wallpaper]
enabled = false

[widget.workspaces]
active_pill_size = 1.7000000000000002
font_scale = 0.75
font_weight = 700
inactive_pill_size = 0.25
occupied_color = "outline"
pill_scale = 0.84999999999999998
style = "minimal"
